[package]
name = "rusk-uplink_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.*", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
derive-new = "0.5"
